### ISSUE TITLE
I don't understand this

### ISSUE THREAD

**Issue by Rufulus86** [ddd-Makbema/gameEngine#17]
The read me is not user friendly and I don't understand how to do anything with the code. Pygame is its own game engine already. Why are we even doing this at all? Also quite frankly, I really do not enjoy working on this code at all. Why should i have to be doing this. I am not a Guinea Pig.

**Comment by ddd-Makbema** [comment]
1: what is unclear in the readme that could be changed to make it better
2: this project is using pygame as a base to make a visual game engine similar to unity (if you want examples, look up unity engine)
3: if you have another project you would like to work on I'm fine with that but to me, it seems like you don't have direction for what to do and this is a way for you to dip your feet into a bigger project.

**Comment by multum-non-multa** [comment]
(Somewhat) agreed --- and it is up to the developer to provide "direction."
